### ISSUE TITLE
Invalid args in tutorial

### ISSUE THREAD

**Issue by Charles-Fieseler-Vienna** [focolab/NWBelegans#10]
In this section of the tutorial I get a crash:

```
OpticalChannelRefs = OpticalChannelReferences(
    name = 'OpticalChannelRefs',
    channels = OptChanRefData
)
```

TypeError: CustomClassGenerator.set_init.<locals>.__init__: missing argument 'data', unrecognized argument: 'channels'

Full error:
    532     OptChanRefData.append(wave)
    534 # This object just contains references to the order of channels because OptChannels does not preserve ordering by itself
--> 535 OpticalChannelRefs = OpticalChannelReferences(
    536     name='OpticalChannelRefs',
    537     channels=OptChanRefData
    538 )
    540 ImagingVol = ImagingVolume(
    541     name='NeuroPALImVol',
    542     # Add connections to the OptChannels and OpticalChannelRefs objects
   (...)
    561     reference_frame="Worm head"
    562 )
    564 nwbfile.add_imaging_plane(ImagingVol)  # add this ImagingVol to the nwbfile

File ~/anaconda3/envs/wbfm38/lib/python3.8/site-packages/hdmf/utils.py:643, in docval.<locals>.dec.<locals>.func_call(*args, **kwargs)
    642 def func_call(*args, **kwargs):
--> 643     pargs = _check_args(args, kwargs)
    644     return func(args[0], **pargs)

File ~/anaconda3/envs/wbfm38/lib/python3.8/site-packages/hdmf/utils.py:636, in docval.<locals>.dec.<locals>._check_args(args, kwargs)
    634     if parse_err:
    635         msg = '%s: %s' % (func.__qualname__, ', '.join(parse_err))
--> 636         raise Exception

**Comment by dysprague** [comment]
Have you checked that you the ndx-multichannel-volume extension package is updated? The latest is 0.1.11. Also is this using your own data or the example data given in the tutorial?

I have not seen this issue before so I'm not sure what might be causing it. If you could try with the latest ndx-multichannel-volume package and with the example data in the box folder linked in the tutorial that would be great. Otherwise, I'll try to recreate and trackdown that error

**Comment by Charles-Fieseler-Vienna** [comment]
Ah, I had updated the repo but not ndx-multichannel-volume.

Fixed!
