### ISSUE TITLE
Best practice for behavior metadata

### ISSUE THREAD

**Issue by Charles-Fieseler-Vienna** [focolab/NWBelegans#5]
Again I'm asking questions that you probably haven't dealt with, sorry! Hopefully these are easy to answer, and I'll just confirm my understanding and propose some standard names:

We have many behavior measurements, including:
1. Kymograph (curvature across body across time): 2d, could be pynwb.behavior.SpatialSeries called "kymograph" or "kymogram"
2. Speed: 1d, could just be a  pynwb.behavior.BehavioralTimeSeries called "speed" (not velocity)
3. Position: 1d, probably should be  pynwb.behavior.Position called "stage_position" or "centroid_position" 
4. Behavioral states: 1d, but sometimes have overlapping (e.g. Reversal + turn vs. Forward + turn)... could be pynwb.behavior.BehavioralEpochs or a list of these?

Thanks again for your work!

**Comment by dysprague** [comment]
Responding here! I have not really taken a look at much of the behavioral stuff before, but looking over your suggestions and can give some thoughts!

1. I think the SpatialSeries makes sense for the kymograph. It allows for 2D data and allows you to specify the units and add a description, so I think it has all the data needed to cover kymograph data. For the name I think you should be more descriptive since there are different types of kymographs you could have. Maybe something more like 'BodyCurveKymograph'. If there are other types of data we should include in the kymograph data we can certainly also define a 'kymograph' extensions object.
2. Speed should be pretty straightforward and I think BehavioralTimeSeries covers it. I think 'Speed' is probably a sufficiently descriptive name
3. Position should also be pretty straightforward and the Position object should cover it. I like "StagePosition" as a name
4. I think BehavioralEpochs makes sense. The only slight limitation of this approach is I think every different type of behavior would need its own IntervalSeries. So the data input to BehavioralEpochs would end up being a list of IntervalSeries objects for each type of behavior you're recording (e.g. reversal, forward movement, turn, etc.). You could also definitely have overlapping behaviors since they would all be stored in different IntervalSeries objects. Alternatively, if you want to store all behavior in one data object, you could use the more general pynwb.epoch.TimeIntervals object which would create a data table of intervals where you can define extra columns to add labels to each time interval.

If you haven't seen this already, it would be great to take a look at the [pynwb behavioral tutorial](https://pynwb.readthedocs.io/en/stable/tutorials/domain/plot_behavior.html#sphx-glr-tutorials-domain-plot-behavior-py) which has lots of great examples of using the behavioral objects.

I think it's great to be as standard as possible with the naming conventions, but I don't think we have to be as prescriptive for behavioral data since every lab will have likely very different experiments they're running. I think it's most important to 100% standardize the naming and formatting for NeuroPAL images and Calcium images. Although I would love for this to be a bigger discussion amongst the worm community about the extent of standardization we want.

**Comment by dysprague** [comment]
Closing this for now but feel free to add another issue if you have other questions
